config/routes.rb
Rails.application.routes.draw do
  
  root 'top#main'
  get 'top/main'
  resources :products
  resources :cartitems, only: [:create, :destroy]
  resources :carts, only: [:show]

end

app/models/cart.rb
class Cart < ActiveRecord::Base
    has_many :cartitems
end

app/models/cartitem.rb
class Cartitem < ActiveRecord::Base
    belongs_to :product
    belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
    has_one :cartitem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  private
  def current_cart
    if session[:cart_id]
      cart = Cart.find(session[:cart_id])
    else
      cart = Cart.create
      session[:cart_id] = cart.id
    end
    cart
  end
  helper_method :current_cart
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
    
    def create
        cart = Cart.find(session[:cart_id])
        p pro = Product.find(params[:id])
        cartitem = Cartitem.new(qty: params[:qty], product_id: pro.id, cart_id: cart.id )
        cartitem.product = pro
        cart.cartitems << cartitem
        cartitem.save
        
        redirect_to products_path
    end
    
    def destroy
        cow = params[:id]
        Cartitem.destroy_all(product_id: cow, cart_id: session[:cart_id])
        redirect_to products_path
    end
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    
    def show
        @cartitem = Cartitem.all
        @cart = Cart.find(session[:cart_id])
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    def index
        @products = Product.all
        @cartitem = Cartitem.all
    end
    
    def new
        @product = Product.new
    end
    
    def create
        name = params[:product][:name]
        price = params[:product][:price]
        
        product = Product.new(name: name, price: price)
        product.save
        redirect_to products_path
    end
    
    def destroy
        product = Product.find(params[:id])
        product.destroy
        redirect_to products_path
    end
    
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    before_action :current_cart
    
    def main
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<h1>carts#show</h1>
<hr>
<tbody>
    <% for cow in 1..@cartitem.maximum(:product_id) do %>
    <% c = @cartitem.where(product_id: cow) %>
    <% if c.where(cart_id:@cart.id).count > 0 %>
       <tr>
           <td><%= "商品名:" %><%= c.first.product.name %>&nbsp;&nbsp;</td>
           <td><%= "価格:" %><%= c.first.product.price %><%= "円" %>&nbsp;&nbsp;</td>
           <td><%= "注文数:" %><%= c.sum(:qty) %><%= "個" %>&nbsp;&nbsp;</td>
           <td><%= "お支払額:" %><%= c.sum(:qty) * c.first.product.price %><%= "円" %>&nbsp;&nbsp;</td>
           <td><%= link_to "   注文取り消し", cartitem_path(cow), method: :delete %></td>
       </tr></br><hr>
    <% end %>
    <% end %>
</tbody>

<p><%= link_to "R.T.B.", products_path, method: :get %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Siberia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>products#index</h1>
<%= link_to '商品追加', new_product_path %>
<%= link_to 'カートを見る', cart_path(@cartitem), method: :get %>
<hr>
<tbody>
   <% @products.each do |prdct| %>
      <tr>
          <td><%= prdct.name %><%= " " %></td>
          <td><%= prdct.price %><%= "円" %></td>
          <td>
              <%= form_tag(cartitems_path, method: :post) do %>
              <%= label_tag :個数 %>
              <%= number_field_tag :qty %>
              <%= hidden_field_tag :id, prdct.id %>
          </td>
          <td><%= submit_tag "カートに入れる" %></td>
          <td><%= link_to '商品を削除', product_path(prdct.id), method: :delete %></td>
          <% end %>
    <% end %>
</tbody>

app/views/products/new.html.erb
<h1>products#new</h1>
<hr>
<%= form_for @product, url: {action: :create} do |prdct| %>
   <%= prdct.label :商品名 %>
   <%= prdct.text_field :name %>
   <%= prdct.label :価格 %>
   <%= prdct.number_field :price %>
   <p><%= prdct.submit "確定" ,  data: {confirm: '登録しますか?'} %></p>
<% end %>

app/views/top/main.html.erb
<h1>top#main</h1>
<strong>なにもない</strong>
<hr>
<p><%= link_to "商品一覧", products_path, method: :get %></p>